# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgIVNBWt3Dc4ttvD9BOMAglWs8sqULXu
"""
import matplotlib
import matplotlib.pyplot as plt

# create some data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# create a line plot
plt.plot(x, y)

# display the plot
plt.show()

import matplotlib.pyplot as plt

# create some data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# create a line plot
plt.plot(x, y)

# display the plot
plt.savefig("bot1.png")
