#! python3
# launch map in browser using an address from the command line
# import pyperclip and use address = pyperclip.paste for clipboard use

import webbrowser, sys

# If there is at least one command line argument
if len(sys.argv) > 1:
    address = ' '.join(sys.argv[1:])
    
    # Open the web browser with the constructed URL
    webbrowser.open('https://www.google.com/maps/place/' + address)

# Write sys.argv to a file and print to the screen
filename = "address.txt"
with open(filename, "w") as file:
    print("Contents of sys.argv:")
    for arg in sys.argv:
        # Write each argument to the file
        file.write(arg + "\n")

# Print confirmation message
print(f"sys.argv has been written to {filename}")
