#! python3
# searchpypi.py - opens several search results

# import required modules
import requests, sys, webbrowser, bs4

# download search result page
print('Searching...')
res = requests.get('https://pypi.org/?q=' + ' '.join(sys.argv[1:]))
res.raise_for_status()

# Retrieve top search result links
soup = bs4.BeautifulSoup(res.text, 'html.parser')

# Select link elements with the CSS clas 'package-snippet'
linkElements = soup.select('.package-snippet')
# We want at most 5 search results
numOpen = min(5, len(linkElements))

for i in range(numOpen):
    urlToOpen = 'https://pypi.org' + linkElements[i].get('href')
    print('Opening', urlToOpen)
    webbrowser.open(urlToOpen)
